export const domains = [
    'Computer Science',
    'Physics',
    'Philosophy',
    'Design',
    'Art',
    'Electrical Engineering',
    'Software Engineering',
    'Aerospace Engineering',
    'Mechanical Engineering',
    'Biology',
    'Chemestry',
    'Mathematics',
    'Literature',
    'Music',
    'Law',
    'Business',
    'Economics',
    'Political Science',
    'Arquitecture',
    'Anthropology',
    'Medicine',
    'Education',
];

export const origins = [
    'Personal Experience',
    'Book',
    'Lecture',
    'Film',
    'Theater Play',
    'Video',
    'Video Game',
    'Song',
    'Article',
    'Relation',
    'Lesson',
    'Interpretation',
];