/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Book(props) {
  const { nodes, materials } = useGLTF('/models/book.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pages.geometry}
        material={materials.Material}
        position={[0.01, 0.02, 0.14]}
        scale={[1.38, 0.11, 1.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cover.geometry}
        material={materials.cover}
        position={[0.01, 0.02, 1.26]}
        scale={[1.52, 0.14, 0.05]}
      />
    </group>
  );
}

useGLTF.preload('/models/book.glb');
