/*
Auto-generated by: https://github.com/pmndrs/gltfjsx 
https://gltf.pmnd.rs/
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Chalkboard(props) {
  const { nodes, materials } = useGLTF('/models/chalkboard2.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={[2.2, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.board}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials.border}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/chalkboard2.glb');
