/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Newspaper(props) {

  const { nodes, materials } = useGLTF('/models/newspaper2.glb');
  const mesh = useRef();
  const [hovered, setHovered] = useState(false);

  useFrame((state, delta) => {
    if( hovered ){
      mesh.current.rotation.z += delta
    }
    else if(mesh.current.rotation.z > 0.01 ){
      mesh.current.rotation.z -= delta
    }
  })


  return (
    <group {...props} dispose={null}>
      <mesh
        ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.np_mid.geometry}
        material={materials['newspaper_page-0001']}
        scale={5}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
    </group>
  );
}

useGLTF.preload('/models/newspaper2.glb');
