/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Theater(props) {
  const { nodes, materials } = useGLTF('/models/theater.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.masks.geometry}
        material={materials['tragcom-removebg-preview']}
        scale={3}
      />
    </group>
  );
}

useGLTF.preload('/models/theater.glb');
