/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Video(props) {
  const { nodes, materials } = useGLTF('/models/video.glb');
  return (
    <group {...props} dispose={null} scale={0.7}>
      <group
        position={[1, 0.09, -0.16]}
        rotation={[0, Math.PI / 4, 0]}
        scale={[0.09, 0.02, 0.09]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials.keyboard}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={nodes.Cube011_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_2.geometry}
          material={materials.play}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_3.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/video.glb');
